[project]
name = "deepdoc-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = [
    "numpy==1.26.4",
    "requests==2.32.3",
    "tiktoken>=0.9.0",
]
